/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku.gui;

import com.sun.glass.events.KeyEvent;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import sudoku.SudokuSolver;

/**
 *
 * @author Ameljo
 */
public class SudokuGui extends javax.swing.JFrame
{

    /**
     * Creates new form SudokuGui
     */
    public SudokuGui()
    {
        this.sudokuArray = new ArrayList<javax.swing.JTextField>();
        initComponents();
    }
    ///sfds

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sudokuPanel = new javax.swing.JPanel();
        textField_1_1 = new javax.swing.JTextField();
        textField_1_2 = new javax.swing.JTextField();
        textField_1_3 = new javax.swing.JTextField();
        textField_1_4 = new javax.swing.JTextField();
        textField_1_5 = new javax.swing.JTextField();
        textField_1_6 = new javax.swing.JTextField();
        textField_1_7 = new javax.swing.JTextField();
        textField_1_8 = new javax.swing.JTextField();
        textField_1_9 = new javax.swing.JTextField();
        textField_2_1 = new javax.swing.JTextField();
        textField_2_2 = new javax.swing.JTextField();
        textField_2_3 = new javax.swing.JTextField();
        textField_2_4 = new javax.swing.JTextField();
        textField_2_5 = new javax.swing.JTextField();
        textField_2_6 = new javax.swing.JTextField();
        textField_2_7 = new javax.swing.JTextField();
        textField_2_8 = new javax.swing.JTextField();
        textField_2_9 = new javax.swing.JTextField();
        textField_3_1 = new javax.swing.JTextField();
        textField_3_2 = new javax.swing.JTextField();
        textField_3_3 = new javax.swing.JTextField();
        textField_3_4 = new javax.swing.JTextField();
        textField_3_5 = new javax.swing.JTextField();
        textField_3_6 = new javax.swing.JTextField();
        textField_3_7 = new javax.swing.JTextField();
        textField_3_8 = new javax.swing.JTextField();
        textField_3_9 = new javax.swing.JTextField();
        textField_4_1 = new javax.swing.JTextField();
        textField_4_2 = new javax.swing.JTextField();
        textField_4_3 = new javax.swing.JTextField();
        textField_4_4 = new javax.swing.JTextField();
        textField_4_5 = new javax.swing.JTextField();
        textField_4_6 = new javax.swing.JTextField();
        textField_4_7 = new javax.swing.JTextField();
        textField_4_8 = new javax.swing.JTextField();
        textField_4_9 = new javax.swing.JTextField();
        textField_5_1 = new javax.swing.JTextField();
        textField_5_2 = new javax.swing.JTextField();
        textField_5_3 = new javax.swing.JTextField();
        textField_5_4 = new javax.swing.JTextField();
        textField_5_5 = new javax.swing.JTextField();
        textField_5_6 = new javax.swing.JTextField();
        textField_5_7 = new javax.swing.JTextField();
        textField_5_8 = new javax.swing.JTextField();
        textField_5_9 = new javax.swing.JTextField();
        textField_6_1 = new javax.swing.JTextField();
        textField_6_2 = new javax.swing.JTextField();
        textField_6_3 = new javax.swing.JTextField();
        textField_6_4 = new javax.swing.JTextField();
        textField_6_5 = new javax.swing.JTextField();
        textField_6_6 = new javax.swing.JTextField();
        textField_6_7 = new javax.swing.JTextField();
        textField_6_8 = new javax.swing.JTextField();
        textField_6_9 = new javax.swing.JTextField();
        textField_7_1 = new javax.swing.JTextField();
        textField_7_2 = new javax.swing.JTextField();
        textField_7_3 = new javax.swing.JTextField();
        textField_7_4 = new javax.swing.JTextField();
        textField_7_5 = new javax.swing.JTextField();
        textField_7_6 = new javax.swing.JTextField();
        textField_7_7 = new javax.swing.JTextField();
        textField_7_8 = new javax.swing.JTextField();
        textField_7_9 = new javax.swing.JTextField();
        textField_8_1 = new javax.swing.JTextField();
        textField_8_2 = new javax.swing.JTextField();
        textField_8_3 = new javax.swing.JTextField();
        textField_8_4 = new javax.swing.JTextField();
        textField_8_5 = new javax.swing.JTextField();
        textField_8_6 = new javax.swing.JTextField();
        textField_8_7 = new javax.swing.JTextField();
        textField_8_8 = new javax.swing.JTextField();
        textField_8_9 = new javax.swing.JTextField();
        textField_9_1 = new javax.swing.JTextField();
        textField_9_2 = new javax.swing.JTextField();
        textField_9_3 = new javax.swing.JTextField();
        textField_9_4 = new javax.swing.JTextField();
        textField_9_5 = new javax.swing.JTextField();
        textField_9_6 = new javax.swing.JTextField();
        textField_9_7 = new javax.swing.JTextField();
        textField_9_8 = new javax.swing.JTextField();
        textField_9_9 = new javax.swing.JTextField();
        solveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Solver");
        setBackground(new java.awt.Color(255, 255, 255)
        );
        setFocusCycleRoot(false);
        setIconImage(new 
            ImageIcon(getClass().getResource("sudoku.jpg")).getImage());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        sudokuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sudokuPanel.setPreferredSize(new java.awt.Dimension(243, 243));
        sudokuPanel.setLayout(new java.awt.GridLayout(9, 9));

        sudokuArray.add(textField_1_1);
        textField_1_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_1_1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_1_1);

        sudokuArray.add(textField_1_2);
        textField_1_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_1_2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_1_2);

        sudokuArray.add(textField_1_3);
        textField_1_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_1_3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_1_3);

        sudokuArray.add(textField_1_4);
        textField_1_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_1_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_1_4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        textField_1_4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textField_1_4ActionPerformed(evt);
            }
        });
        sudokuPanel.add(textField_1_4);

        sudokuArray.add(textField_1_5);
        textField_1_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_1_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_1_5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_1_5);

        sudokuArray.add(textField_1_6);
        textField_1_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_1_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_1_6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_1_6);

        sudokuArray.add(textField_1_7);
        textField_1_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_1_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_1_7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_1_7);

        sudokuArray.add(textField_1_8);
        textField_1_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_1_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_1_8.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_1_8);

        sudokuArray.add(textField_1_9);
        textField_1_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_1_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_1_9.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_1_9);

        sudokuArray.add(textField_2_1);
        textField_2_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_2_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_2_1);

        sudokuArray.add(textField_2_2);
        textField_2_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_2_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_2_2);

        sudokuArray.add(textField_2_3);
        textField_2_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_2_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_2_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_2_3);

        sudokuArray.add(textField_2_4);
        textField_2_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_2_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_2_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_2_4);

        sudokuArray.add(textField_2_5);
        textField_2_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_2_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_2_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_2_5);

        sudokuArray.add(textField_2_6);
        textField_2_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_2_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_2_6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_2_6);

        sudokuArray.add(textField_2_7);
        textField_2_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_2_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_2_7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_2_7);

        sudokuArray.add(textField_2_8);
        textField_2_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_2_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_2_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_2_8);

        sudokuArray.add(textField_2_9);
        textField_2_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_2_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_2_9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_2_9);

        sudokuArray.add(textField_3_1);
        textField_3_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_3_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_3_1);

        sudokuArray.add(textField_3_2);
        textField_3_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_3_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_3_2);

        sudokuArray.add(textField_3_3);
        textField_3_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_3_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_3_3);

        sudokuArray.add(textField_3_4);
        textField_3_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_3_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_3_4);

        sudokuArray.add(textField_3_5);
        textField_3_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_3_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3_5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_3_5);

        sudokuArray.add(textField_3_6);
        textField_3_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_3_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3_6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_3_6);

        sudokuArray.add(textField_3_7);
        textField_3_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_3_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3_7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_3_7);

        sudokuArray.add(textField_3_8);
        textField_3_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_3_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3_8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_3_8);

        sudokuArray.add(textField_3_9);
        textField_3_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_3_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_3_9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_3_9);

        sudokuArray.add(textField_4_1);
        textField_4_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_4_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4_1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_4_1);

        sudokuArray.add(textField_4_2);
        textField_4_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_4_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4_2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_4_2);

        sudokuArray.add(textField_4_3);
        textField_4_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_4_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4_3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_4_3);

        sudokuArray.add(textField_4_4);
        textField_4_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_4_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4_4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_4_4);

        sudokuArray.add(textField_4_5);
        textField_4_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_4_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4_5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_4_5);

        sudokuArray.add(textField_4_6);
        textField_4_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_4_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4_6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_4_6);

        sudokuArray.add(textField_4_7);
        textField_4_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_4_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4_7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_4_7);

        sudokuArray.add(textField_4_8);
        textField_4_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_4_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4_8.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_4_8);

        sudokuArray.add(textField_4_9);
        textField_4_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_4_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_4_9.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_4_9);

        sudokuArray.add(textField_5_1);
        textField_5_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_5_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_5_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_5_1);

        sudokuArray.add(textField_5_2);
        textField_5_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_5_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_5_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_5_2);

        sudokuArray.add(textField_5_3);
        textField_5_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_5_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_5_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_5_3);

        sudokuArray.add(textField_5_4);
        textField_5_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_5_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_5_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_5_4);

        sudokuArray.add(textField_5_5);
        textField_5_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_5_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_5_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_5_5);

        sudokuArray.add(textField_5_6);
        textField_5_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_5_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_5_6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_5_6);

        sudokuArray.add(textField_5_7);
        textField_5_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_5_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_5_7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_5_7);

        sudokuArray.add(textField_5_8);
        textField_5_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_5_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_5_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_5_8);

        sudokuArray.add(textField_5_9);
        textField_5_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_5_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_5_9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_5_9);

        sudokuArray.add(textField_6_1);
        textField_6_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_6_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_6_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_6_1);

        sudokuArray.add(textField_6_2);
        textField_6_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_6_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_6_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_6_2);

        sudokuArray.add(textField_6_3);
        textField_6_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_6_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_6_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_6_3);

        sudokuArray.add(textField_6_4);
        textField_6_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_6_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_6_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_6_4);

        sudokuArray.add(textField_6_5);
        textField_6_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_6_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_6_5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_6_5);

        sudokuArray.add(textField_6_6);
        textField_6_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_6_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_6_6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_6_6);

        sudokuArray.add(textField_6_7);
        textField_6_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_6_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_6_7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_6_7);

        sudokuArray.add(textField_6_8);
        textField_6_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_6_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_6_8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_6_8);

        sudokuArray.add(textField_6_9);
        textField_6_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_6_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_6_9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_6_9);

        sudokuArray.add(textField_7_1);
        textField_7_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_7_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_7_1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_7_1);

        sudokuArray.add(textField_7_2);
        textField_7_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_7_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_7_2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_7_2);

        sudokuArray.add(textField_7_3);
        textField_7_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_7_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_7_3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_7_3);

        sudokuArray.add(textField_7_4);
        textField_7_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_7_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_7_4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_7_4);

        sudokuArray.add(textField_7_5);
        textField_7_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_7_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_7_5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_7_5);

        sudokuArray.add(textField_7_6);
        textField_7_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_7_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_7_6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_7_6);

        sudokuArray.add(textField_7_7);
        textField_7_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_7_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_7_7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_7_7);

        sudokuArray.add(textField_7_8);
        textField_7_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_7_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_7_8.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_7_8);

        sudokuArray.add(textField_7_9);
        textField_7_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_7_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_7_9.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_7_9);

        sudokuArray.add(textField_8_1);
        textField_8_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_8_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_8_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_8_1);

        sudokuArray.add(textField_8_2);
        textField_8_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_8_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_8_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_8_2);

        sudokuArray.add(textField_8_3);
        textField_8_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_8_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_8_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_8_3);

        sudokuArray.add(textField_8_4);
        textField_8_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_8_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_8_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_8_4);

        sudokuArray.add(textField_8_5);
        textField_8_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_8_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_8_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_8_5);

        sudokuArray.add(textField_8_6);
        textField_8_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_8_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_8_6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_8_6);

        sudokuArray.add(textField_8_7);
        textField_8_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_8_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_8_7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_8_7);

        sudokuArray.add(textField_8_8);
        textField_8_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_8_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_8_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_8_8);

        sudokuArray.add(textField_8_9);
        textField_8_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_8_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_8_9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_8_9);

        sudokuArray.add(textField_9_1);
        textField_9_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_9_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_9_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_9_1);

        sudokuArray.add(textField_9_2);
        textField_9_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_9_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_9_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_9_2);

        sudokuArray.add(textField_9_3);
        textField_9_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_9_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_9_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_9_3);

        sudokuArray.add(textField_9_4);
        textField_9_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_9_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_9_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_9_4);

        sudokuArray.add(textField_9_5);
        textField_9_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_9_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_9_5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_9_5);

        sudokuArray.add(textField_9_6);
        textField_9_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_9_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_9_6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_9_6);

        sudokuArray.add(textField_9_7);
        textField_9_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_9_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_9_7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_9_7);

        sudokuArray.add(textField_9_8);
        textField_9_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_9_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_9_8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_9_8);

        sudokuArray.add(textField_9_9);
        textField_9_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textField_9_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_9_9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        sudokuPanel.add(textField_9_9);

        solveBtn.requestFocus();
        solveBtn.setText("Solve");
        solveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                solveBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setForeground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        jPanel2.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        jPanel2.add(jLabel2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("3");
        jPanel2.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("4");
        jPanel2.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("5");
        jPanel2.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("6");
        jPanel2.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("7");
        jPanel2.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("8");
        jPanel2.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("9");
        jPanel2.add(jLabel10);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(new java.awt.GridLayout(9, 1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("1");
        jPanel3.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("2");
        jPanel3.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("3");
        jPanel3.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("4");
        jPanel3.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("5");
        jPanel3.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("6");
        jPanel3.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("7");
        jPanel3.add(jLabel17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("8");
        jPanel3.add(jLabel18);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("9");
        jPanel3.add(jLabel19);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sudokuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(solveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sudokuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_solveBtnActionPerformed
    {//GEN-HEADEREND:event_solveBtnActionPerformed
        // TODO add your handling code here:
        SudokuSolver solve = new SudokuSolver(this.sudokuArray);
        solve.solve();
    }//GEN-LAST:event_solveBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearBtnActionPerformed
    {//GEN-HEADEREND:event_clearBtnActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < sudokuArray.size() ;i++)
            sudokuArray.get(i).setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void textField_1_4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textField_1_4ActionPerformed
    {//GEN-HEADEREND:event_textField_1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_1_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SudokuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SudokuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SudokuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SudokuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SudokuGui().setVisible(true);
            }
        });
    }

    private List<javax.swing.JTextField> sudokuArray;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton solveBtn;
    private javax.swing.JPanel sudokuPanel;
    private javax.swing.JTextField textField_1_1;
    private javax.swing.JTextField textField_1_2;
    private javax.swing.JTextField textField_1_3;
    private javax.swing.JTextField textField_1_4;
    private javax.swing.JTextField textField_1_5;
    private javax.swing.JTextField textField_1_6;
    private javax.swing.JTextField textField_1_7;
    private javax.swing.JTextField textField_1_8;
    private javax.swing.JTextField textField_1_9;
    private javax.swing.JTextField textField_2_1;
    private javax.swing.JTextField textField_2_2;
    private javax.swing.JTextField textField_2_3;
    private javax.swing.JTextField textField_2_4;
    private javax.swing.JTextField textField_2_5;
    private javax.swing.JTextField textField_2_6;
    private javax.swing.JTextField textField_2_7;
    private javax.swing.JTextField textField_2_8;
    private javax.swing.JTextField textField_2_9;
    private javax.swing.JTextField textField_3_1;
    private javax.swing.JTextField textField_3_2;
    private javax.swing.JTextField textField_3_3;
    private javax.swing.JTextField textField_3_4;
    private javax.swing.JTextField textField_3_5;
    private javax.swing.JTextField textField_3_6;
    private javax.swing.JTextField textField_3_7;
    private javax.swing.JTextField textField_3_8;
    private javax.swing.JTextField textField_3_9;
    private javax.swing.JTextField textField_4_1;
    private javax.swing.JTextField textField_4_2;
    private javax.swing.JTextField textField_4_3;
    private javax.swing.JTextField textField_4_4;
    private javax.swing.JTextField textField_4_5;
    private javax.swing.JTextField textField_4_6;
    private javax.swing.JTextField textField_4_7;
    private javax.swing.JTextField textField_4_8;
    private javax.swing.JTextField textField_4_9;
    private javax.swing.JTextField textField_5_1;
    private javax.swing.JTextField textField_5_2;
    private javax.swing.JTextField textField_5_3;
    private javax.swing.JTextField textField_5_4;
    private javax.swing.JTextField textField_5_5;
    private javax.swing.JTextField textField_5_6;
    private javax.swing.JTextField textField_5_7;
    private javax.swing.JTextField textField_5_8;
    private javax.swing.JTextField textField_5_9;
    private javax.swing.JTextField textField_6_1;
    private javax.swing.JTextField textField_6_2;
    private javax.swing.JTextField textField_6_3;
    private javax.swing.JTextField textField_6_4;
    private javax.swing.JTextField textField_6_5;
    private javax.swing.JTextField textField_6_6;
    private javax.swing.JTextField textField_6_7;
    private javax.swing.JTextField textField_6_8;
    private javax.swing.JTextField textField_6_9;
    private javax.swing.JTextField textField_7_1;
    private javax.swing.JTextField textField_7_2;
    private javax.swing.JTextField textField_7_3;
    private javax.swing.JTextField textField_7_4;
    private javax.swing.JTextField textField_7_5;
    private javax.swing.JTextField textField_7_6;
    private javax.swing.JTextField textField_7_7;
    private javax.swing.JTextField textField_7_8;
    private javax.swing.JTextField textField_7_9;
    private javax.swing.JTextField textField_8_1;
    private javax.swing.JTextField textField_8_2;
    private javax.swing.JTextField textField_8_3;
    private javax.swing.JTextField textField_8_4;
    private javax.swing.JTextField textField_8_5;
    private javax.swing.JTextField textField_8_6;
    private javax.swing.JTextField textField_8_7;
    private javax.swing.JTextField textField_8_8;
    private javax.swing.JTextField textField_8_9;
    private javax.swing.JTextField textField_9_1;
    private javax.swing.JTextField textField_9_2;
    private javax.swing.JTextField textField_9_3;
    private javax.swing.JTextField textField_9_4;
    private javax.swing.JTextField textField_9_5;
    private javax.swing.JTextField textField_9_6;
    private javax.swing.JTextField textField_9_7;
    private javax.swing.JTextField textField_9_8;
    private javax.swing.JTextField textField_9_9;
    // End of variables declaration//GEN-END:variables
}
